
# QSM 1mm to T1, then to MNI
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1.nii -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/T1weighted_Anatomical_9_T1-weighted_Anatomical_20181012133350_9.nii -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii -omat /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12  -interp trilinear
# apply mag MAT FLIRT trans to QSM
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz



# QSM 0.75mm to T1, then to MNI
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1.nii -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/T1weighted_Anatomical_9_T1-weighted_Anatomical_20181012133350_9.nii -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii -omat /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12  -interp trilinear
# apply mag MAT FLIRT trans to QSM
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Js/14902/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz




# QSM 1mm to T1, then to MNI
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1.nii -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/T1weighted_Anatomical_5_T1-weighted_Anatomical_20181012143413_5.nii -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii -omat /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12  -interp trilinear
# apply mag MAT FLIRT trans to QSM
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz

# QSM 0.75mm to T1, then to MNI
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1.nii -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/T1weighted_Anatomical_5_T1-weighted_Anatomical_20181012143413_5.nii -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii -omat /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12  -interp trilinear
# apply mag MAT FLIRT trans to QSM
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Hs/14903/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz





# QSM 0.75mm to T1, then to MNI
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1.nii -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/BRAVO_600_ms_6_BRAVO_600_ms_20180919161434_6.nii -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii -omat /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12  -interp trilinear
# apply mag MAT FLIRT trans to QSM
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Physio_03016/14754/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz






# QSM 1mm to T1, then to MNI
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1.nii -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/BRAVO_pd_4p5s_TI500_2_BRAVO_pd_4p5s_TI500_20180925161329_2.nii.nii -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii -omat /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12  -interp trilinear
# apply mag MAT FLIRT trans to QSM
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_1mm/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz

# QSM 0.75mm to T1, then to MNI
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1.nii -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/BRAVO_pd_4p5s_TI500_2_BRAVO_pd_4p5s_TI500_20180925161329_2.nii.nii -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii -omat /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12  -interp trilinear
# apply mag MAT FLIRT trans to QSM
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/sus_resharp_tik_0.0001_tv_0.0005_num_500_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/chi_iLSQR_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI1500_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI2000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz
/usr/local/fsl/bin/flirt -in /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3.nii -applyxfm -init /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.mat -out /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/RESHARP/MEDI5000_RESHARP_smvrad3_FLIRT.nii -paddingsize 0.0 -interp trilinear -ref /Users/hongfusun/DATA/FGATIR/sorted_dicoms/Dr/14792/QSM_p75/QSM_SPGR_GE/src/mag1_FLIRT.nii.gz

