cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_135/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_061/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_129/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_076/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_049/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_068/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_111/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_121/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_139/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_038/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_122/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_044/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_047/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_034/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_029/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_144/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_111/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_040/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_043/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_105/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_078/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_100/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_066/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_061/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_040/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_080/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_054/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_005/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_139/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_015/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_030/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_073/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_004/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_050/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_044/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_020/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_018/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_077/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_108/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_118/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_058/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_093/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_039/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_045/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_068/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_143/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_097/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_099/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_132/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_069/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_005/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_001/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_015/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_093/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_099/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_066/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_140/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_047/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_087/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_079/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_051/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_060/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_020/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_096/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_041/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_114/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_013/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_058/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_110/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_103/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_057/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_134/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_053/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_048/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_107/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_116/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_092/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_098/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_074/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_014/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_109/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_106/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_128/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_037/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_072/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_137/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_106/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_119/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_095/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_123/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_071/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_092/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_084/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_110/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_091/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_127/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_019/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_063/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_004/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_123/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_027/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_074/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_069/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_060/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_017/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_101/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_100/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_029/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_001/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_138/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_102/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_120/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_104/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_071/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_094/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_095/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_124/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_053/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_025/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_112/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_034/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_081/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_102/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_079/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_051/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_014/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_021/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_062/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_082/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_086/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_017/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_036/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_141/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_046/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_115/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_042/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_052/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_120/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_115/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_023/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_072/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_032/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_097/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_136/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_117/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_121/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_132/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_117/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_031/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_003/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_070/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_041/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_056/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_016/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_105/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_113/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_059/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_094/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_104/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_021/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_114/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_046/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_009/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_042/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_089/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_075/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_022/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_002/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_119/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_057/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_039/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_131/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_035/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_025/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_077/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS14_056/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
cd /media/data/project_preschool/HONG_FU_DATA_DTI/PS15_078/; N4BiasFieldCorrection -i dti_b0.nii -o dti_b0_n4.nii
