cd ./ICHADAPT_II_013/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

cd ./ICHADAPT_II_048/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./ICHADAPT_II_035/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./ICHADAPT_II_034/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./TIAMISO_198/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./TIAMISO_199/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./ICHADAPT_II_011/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./ICHADAPT_II_014/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./TIAMISO_191/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./ICHADAPT_II_046/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./TIAMISO_203/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./TIAMISO_200/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./TIAMISO_190/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./TIAMISO_204/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear

cd ./ICHADAPT_II_043/day2; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_cmb.nii -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_cmb.nii -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_cmb.nii -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_cmb.nii -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear



