cd ./TIAMISO_192/day30; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

cd ./ICHADAPT_II_048/day30; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

cd ./TIAMISO_201/day30; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

cd ./ICHADAPT_II_034/day30; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

cd ./TIAMISO_199/day30; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

cd ./ICHADAPT_II_046/day30; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

cd ./ICHADAPT_II_016/day30; /usr/share/fsl/5.0/bin/flirt -in SAGT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_SAGT1_flipped.nii.gz -omat F_SAGT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXFLAIR_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXFLAIR_flipped.nii.gz -omat F_AXFLAIR_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT1_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT1_flipped.nii.gz -omat F_AXT1_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; /usr/share/fsl/5.0/bin/flirt -in AXT2_flipped.nii.gz -ref mag_flirt.nii.gz -out F_AXT2_flipped.nii.gz -omat F_AXT2_flipped.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp trilinear; cd -;

